### PR TITLE
Add a list of all matches

### PR DESCRIPTION
**Pull request by Serneum**
This does not include pagination

Closes #17

### CODE REVIEW

**Comment by jlholm** [comment]
Your choice if you want to commit as is without pagination. No reason we can't come back to it later after we get the other stuff implemented

**Comment by jlholm** [comment]
@Serneum Let me know if you want me to merge this or if you are wanting to add pagination

**Comment by jlholm** [comment]
@Serneum You can rebase this branch and tests should pass

**Comment by Serneum** [comment]
@JLHOLM this should be ready for review / merge

**Review by jlholm — APPROVED** [review]
LGTM

**Pull request merged**
